@echo off

REM Associate File Extensions
assoc .001=7-Zip.001
assoc .7z=7-Zip.7z
assoc .arj=7-Zip.arj
assoc .bz2=7-Zip.bz2
assoc .bzip2=7-Zip.bzip2
assoc .cpio=7-Zip.cpio
assoc .deb=7-Zip.deb
assoc .dmg=7-Zip.dmg
assoc .fat=7-Zip.fat
assoc .gz=7-Zip.gz
assoc .gzip=7-Zip.gzip
assoc .hfs=7-Zip.hfs
assoc .lha=7-Zip.lha
assoc .lzh=7-Zip.lzh
assoc .lzma=7-Zip.lzma
assoc .ntfs=7-Zip.ntfs
assoc .rar=7-Zip.rar
assoc .rpm=7-Zip.rpm
assoc .squashfs=7-Zip.squashfs
assoc .swm=7-Zip.swm
assoc .tar=7-Zip.tar
assoc .taz=7-Zip.taz
assoc .tbz=7-Zip.tbz
assoc .tbz2=7-Zip.tbz2
assoc .tgz=7-Zip.tgz
assoc .tpz=7-Zip.tpz
assoc .txz=7-Zip.txz
assoc .wim=7-Zip.wim
assoc .xar=7-Zip.xar
assoc .xz=7-Zip.xz
assoc .z=7-Zip.z
assoc .zip=7-Zip.zip
assoc .zipx=zipx_auto_file

ftype 7-Zip.001="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.7z="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.arj="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.bz2="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.bzip2="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.cpio="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.deb="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.dmg="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.fat="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.gz="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.gzip="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.hfs="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.lha="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.lzh="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.lzma="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.ntfs="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.rar="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.rpm="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.squashfs="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.swm="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.tar="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.taz="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.tbz="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.tbz2="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.tgz="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.tpz="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.txz="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.wim="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.xar="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.xz="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.z="C:\Program Files\7-Zip\7zFM.exe" "%%1"
ftype 7-Zip.zip="C:\Program Files\7-Zip\7zFM.exe" "%%1"

